### ISSUE TITLE
Replace Existing DNS Manager with ExternalDNS

### ISSUE THREAD

**Issue by danehans** [openshift/cluster-ingress-operator#77]
[ExternalDNS](https://github.com/kubernetes-incubator/external-dns) supports a wide range of DNS providers, including AWS Route53. Replacing the existing DNS Manager with ExternalDNS will provide a wide range of DNS providers as OpenShift supports future deployment environments. Thoughts?

**Comment by ironcladlou** [comment]
ExternalDNS is definitely our current pick for a sustainable solution to this problem. We need some more discussion around feature gaps, potential consolidation across teams with a similar need, a strategy for (or alternative to) shipping an external-dns image, and probably some other stuff. All tractable problems, IMO.

We as a larger group haven't discussed enough of the use case details to know what the shape of a solution might be yet. For example

1. A "unified theory of DNS management" using a single cluster-scoped ExternalDNS instance
2. Centrally managed but independent ExternalDNS instances to service a set of components
3. Component-managed, independent ExternalDNS instances
4. ???

As far as I can tell, @pmorie has done the most legwork I've seen around wrangling teams and documenting use cases, and @csrwng has done the most practical R&D around using, managing, and contributing to ExternalDNS within the context of OpenShift.

I'm glad you brought this up — it's probably a good time to start coming up with actionable plans. Our bespoke implementation is a stopgap and was designed to be replaced ASAP. We can at least discuss something like (3) above in the context of cluster-ingress-operator specifically so that our use cases can be incorporated into the wider discussion while also enabling us to make independent progress.

/cc @openshift/sig-network-edge @dgoodwin @csrwng @pmorie @ericavonb

**Comment by csrwng** [comment]
The most recent work on the master DNS operator is here: https://github.com/openshift/master-dns-operator. 
@ironcladlou From what I've seen so far, the most practical approach would be 3. We need different instances so we can create records in different zones. For your use case I assume you need the public zone, for mine I need the private zone. And then there's the code that decides what those entries should be. In my case, my operator will create a set of entries based on Cluster API machines that it identifies as masters.

**Comment by ironcladlou** [comment]
We're most likely going to do this, but GitHub is probably not where we're going to track the discussion going forward.
